### ISSUE TITLE
Deleting stream broke plugin

### ISSUE THREAD

**Issue by shokkakhan** [airbus-cyber/graylog-plugin-alert-wizard#105]
Hello -

I deleted a stream that was created by this plugin, this then broke the plugin. When I go to the 'Wizard/Alert Rules' page it provides me with an error saying that a stream cannot be found. The page just says loading, and I cannot create or manage any other alerts.

`Fetching alert rules failed with status: FetchError: There was an error fetching a resource: Not Found. Additional information: org.graylog2.database.NotFoundException: Stream <63a49f20b06e4e56429738a7> not found!`

**Comment by shokkakhan** [comment]
How can I completely remove any traces of this plugin from my Graylog instance? I would like to start fresh.

Removing the .jar file does not uninstall the plugin. The old data is still there, and the drop down menu is still seen at the top of the page.

**Comment by frantz45** [comment]
Hello,

I confirm there is a bug, deleting a Stream (or an Event Definition or a Notification) should not prevent the load of rules.
In previous versions of this plugin it wasn't the case, the problematic rule appeared in red with a "altered" status and we could remove it.
We'll check it and fix it.

If you want to delete to problematic rule in order to recover the access to this plugin web UI:
- If you don't know the URI to connect to MongoDB you can get it from the Graylog configuration file: grep mongodb_uri /etc/graylog/server/server.conf
- Connect to MongoDB (replace the URI with the one you get at the previous step: mongo 'mongodb://localhost/graylog'
- List rules created by this plugin (note the _id of the problematic rule): db.wizard_alerts.find()
- Remove the problematic rule (replace the ID): db.wizard_alerts.remove({"_id": ObjectId("abcdef123456")})
Then refresh your web browser it should work.
Don't forget to remove the old Event Definition and the old Notification.

**Comment by frantz45** [comment]
I've tested with Wizard v5.1.0 and I confirm it's fixed
