### ISSUE TITLE
Incorrect color when switching theme in a THEN rule

### ISSUE THREAD

**Issue by frantz45** [airbus-cyber/graylog-plugin-alert-wizard#118]
1. Create a THEN rule
2. Switch theme dark/light

Some fields's color will not be updated.

**Comment by c8y3** [comment]
I am setting a medium size on this issue, because, this is not necessarily easy to fix since the bug may be in graylog code. So there needs to be an investigation.

**Comment by c8y3** [comment]
The bug seems to be in the Graylog TypeAheadFieldInput component. This component relies on the external js component [typeahead](https://twitter.github.io/typeahead.js/). This component seems to duplicate the input (to show the completion) and copy its style.
But, when the theme is changed, the style of the copy of the input is not updated.
I rewrote the component in our code base. It seems to be working.
However, it would probably be better to open an issue for Graylog to solve, because as it stands we won't benefit from the improvements whenever this component changes (and we now have a slightly larger codebase to maintain)

**Comment by frantz45** [comment]
I confirm it's fixed in Wizard v5.2.0
