### ISSUE TITLE
Deployment to Maven Central failed

### ISSUE THREAD

**Issue by frantz45** [airbus-cyber/graylog-plugin-alert-wizard#122]
https://github.com/airbus-cyber/graylog-plugin-alert-wizard/actions/runs/6314103683/job/17143630745

**Comment by c8y3** [comment]
I put some troubleshooting information here https://github.com/airbus-cyber/graylog-plugin-logging-alert/wiki/Troubleshooting-and-workarounds. However, I am unsure how to fix this problem. Hence the "Medium" size.
In any case, the issue seems related with https://issues.sonatype.org/browse/OSSRH-51097.
The advice seems to be to switch from the current host ([oss.sonatype.org](https://oss.sonatype.org/)) to the new host s01.oss.sonatype.org (https://issues.sonatype.org/browse/OSSRH-51097?focusedId=1168991&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1168991).
To do that, it seems we need to open a migration issue (such as this one https://issues.sonatype.org/browse/OSSRH-76364) on sonatype.org. But do we have an account there? (Maybe our login/password on https://oss.sonatype.org/ will work there too?)


Some more relevant documentation: https://central.sonatype.org/publish/publish-guide/, https://central.sonatype.org/news/20210223_new-users-on-s01/

**Comment by c8y3** [comment]
Some steps to check in order to initiate the correction : 
* check we can log in https://s01.oss.sonatype.org/#welcome (the new server)
* check we can log in JIRA https://issues.sonatype.org/browse/OSSRH-76364 in order to create a ticket
Then discuss again...

**Comment by frantz45** [comment]
@c8y3 @VincentD06 We didn't have this issue to publish the 5.2.0. Can we close this ticket ?

**Comment by frantz45** [comment]
According to @VincentD06 I close the issue
