### ISSUE TITLE
Don't create a stream if there is no stream condition

### ISSUE THREAD

**Issue by frantz45** [airbus-cyber/graylog-plugin-alert-wizard#139]
A stream with no "stream rules" is created when you create a wizard rule with a search query but without stream conditions.
It would be better to not create the stream.

**Comment by c8y3** [comment]
The problem already occurs when there is no conditions at all, for instance when we use the query only.

**Comment by c8y3** [comment]
I will have to add a field matchingType in the data that is persisted. Because, until now, there has always been a stream and it carried this information. So this will break backward compatibility (people will have to export/import their rules). The alternative would be to create a stream anyway, even if it is not going to be used at all. Just to carry this information.

Also the REST API is getting too far away from what we are doing: there is always a stream. At some point, I think we really should simplify the data transported in REST.

**Comment by c8y3** [comment]
When there is no stream, I am going to leave the streams field of the event definitions empty. Except for the correlation count plugin, I am going to set it to the DEFAULT_STREAM. However, I think the correlation count plugin should accept a (possibly empty) list of streams, instead of mandatory stream. Because, if I understand well, the DEFAULT_STREAM contains messages not routed to other streams, which is not exactly the same as all messages.

**Comment by c8y3** [comment]
Will be in the 6.1.0

**Comment by frantz45** [comment]
I confirm it's fixed in v6.1.0
