### ISSUE TITLE
Additional threshold is not correctly displayed

### ISSUE THREAD

**Issue by frantz45** [airbus-cyber/graylog-plugin-alert-wizard#69]
1. Create an "AND" rule
2. Set the main treshold to "more than 0"
3. Set the additional threshold to "less than 1"
4. Fill other required fields
5. Save the rule
6. From the rules list edit the rule

The additional threshold displays "less than 0" instead of "less than 1".
In the Event Definition associated to the rule, the additional threshold is right ("less than 1").
It may be linked with this issue: https://github.com/airbus-cyber/graylog-plugin-alert-wizard/issues/34

My environment:
- Graylog v4.1.11
- Wizard v4.0.0

**Comment by c8y3** [comment]
To create the AND rule:
* set the title to AAA
* set the severity to info
* for the first condition, messages must match all, a matches exactly a, more than 0
* for the second condition, messages must match all, b matches exactly b, less than 1
* messages must come in the last 1 minute
* click save

Then, after creation, check the error by clicking the "edit" button of the rule: the threshold of the second condition is displayed as "less than 0" rather than "less than 1"

**Comment by frantz45** [comment]
Je confirme que le bug est corrigé, je clos l'issue
